package com.priyank.countrypicker

import androidx.fragment.app.FragmentTransaction
import java.util.ArrayList


private val COUNTRIES = arrayOf(
    Country("AD", "Andorra", "+376", R.drawable.flag_ad, "EUR", "€"),
    Country("AE", "United Arab Emirates", "+971", R.drawable.flag_ae, "AED", "د.إ"),
    Country("AF", "Afghanistan", "+93", R.drawable.flag_af, "AFN", "؋"),
    Country("AG", "Antigua and Barbuda", "+1", R.drawable.flag_ag, "XCD", "$"),
    Country("AI", "Anguilla", "+1", R.drawable.flag_ai, "XCD", "$"),
    Country("AL", "Albania", "+355", R.drawable.flag_al, "ALL", "L"),
    Country("AM", "Armenia", "+374", R.drawable.flag_am, "AMD", "֏"),
    Country("AO", "Angola", "+244", R.drawable.flag_ao, "AOA", "Kz"),
    Country("AQ", "Antarctica", "+672", R.drawable.flag_aq, "USD", "$"),
    Country("AR", "Argentina", "+54", R.drawable.flag_ar, "ARS", "$"),
    Country("AS", "American Samoa", "+1", R.drawable.flag_as, "USD", "$"),
    Country("AT", "Austria", "+43", R.drawable.flag_at, "EUR", "€"),
    Country("AU", "Australia", "+61", R.drawable.flag_au, "AUD", "AU$"),
    Country("AW", "Aruba", "+297", R.drawable.flag_aw, "AWG", "Afl"),
    Country("AX", "Aland Islands", "+358", R.drawable.flag_ax, "EUR", "€"),
    Country("AZ", "Azerbaijan", "+994", R.drawable.flag_az, "AZN", "₼"),
    Country("BA", "Bosnia and Herzegovina", "+387", R.drawable.flag_ba, "BAM", "KM"),
    Country("BB", "Barbados", "+1", R.drawable.flag_bb, "BBD", "$"),
    Country("BD", "Bangladesh", "+880", R.drawable.flag_bd, "BDT", " Tk"),
    Country("BE", "Belgium", "+32", R.drawable.flag_be, "EUR", "€"),
    Country("BF", "Burkina Faso", "+226", R.drawable.flag_bf, "XOF", "CFA"),
    Country("BG", "Bulgaria", "+359", R.drawable.flag_bg, "BGN", "лв"),
    Country("BH", "Bahrain", "+973", R.drawable.flag_bh, "BHD", "BD"),
    Country("BI", "Burundi", "+257", R.drawable.flag_bi, "BIF", "FBu"),
    Country("BJ", "Benin", "+229", R.drawable.flag_bj, "XOF", "CFA"),
    Country("BL", "Saint Barthelemy", "+590", R.drawable.flag_bl, "EUR", "€"),
    Country("BM", "Bermuda", "+1", R.drawable.flag_bm, "BMD", "$"),
    Country("BN", "Brunei Darussalam", "+673", R.drawable.flag_bn, "BND", "$"),
    Country(
        "BO",
        "Bolivia, Plurinational State of",
        "+591",
        R.drawable.flag_bo,
        "BOB",
        "${'$'}b"
    ),
    Country("BQ", "Bonaire", "+599", R.drawable.flag_bq, "USD", "$"),
    Country("BR", "Brazil", "+55", R.drawable.flag_br, "BRL", "R$"),
    Country("BS", "Bahamas", "+1", R.drawable.flag_bs, "BSD", "$"),
    Country("BT", "Bhutan", "+975", R.drawable.flag_bt, "BTN", "Nu."),
    Country("BV", "Bouvet Island", "+47", R.drawable.flag_bv, "NOK", "kr"),
    Country("BW", "Botswana", "+267", R.drawable.flag_bw, "BWP", "P"),
    Country("BY", "Belarus", "+375", R.drawable.flag_by, "BYR", "br"),
    Country("BZ", "Belize", "+501", R.drawable.flag_bz, "BZD", "BZ$"),
    Country("CA", "Canada", "+1", R.drawable.flag_ca, "CAD", "$"),
    Country("CC", "Cocos (Keeling) Islands", "+61", R.drawable.flag_cc, "AUD", "AU$"),
    Country("CD", "Congo, The Democratic Republic of the", "+243", R.drawable.flag_cd, "CDF", "FC"),
    Country("CF", "Central African Republic", "+236", R.drawable.flag_cf, "XAF", "FCFA"),
    Country("CG", "Congo", "+242", R.drawable.flag_cg, "XAF", "FCFA"),
    Country("CH", "Switzerland", "+41", R.drawable.flag_ch, "CHF", "CHF"),
    Country("CI", "Ivory Coast", "+225", R.drawable.flag_ci, "XOF", "CFA"),
    Country("CK", "Cook Islands", "+682", R.drawable.flag_ck, "NZD", "$"),
    Country("CL", "Chile", "+56", R.drawable.flag_cl, "CLP", "$"),
    Country("CM", "Cameroon", "+237", R.drawable.flag_cm, "XAF", "FCFA"),
    Country("CN", "China", "+86", R.drawable.flag_cn, "CNY", "¥"),
    Country("CO", "Colombia", "+57", R.drawable.flag_co, "COP", "$"),
    Country("CR", "Costa Rica", "+506", R.drawable.flag_cr, "CRC", "₡"),
    Country("CU", "Cuba", "+53", R.drawable.flag_cu, "CUP", "$"),
    Country("CV", "Cape Verde", "+238", R.drawable.flag_cv, "CVE", "$"),
    Country("CW", "Curacao", "+599", R.drawable.flag_cw, "ANG", "ƒ "),
    Country("CX", "Christmas Island", "+61", R.drawable.flag_cx, "AUD", "AU$"),
    Country("CY", "Cyprus", "+357", R.drawable.flag_cy, "EUR", "€"),
    Country("CZ", "Czech Republic", "+420", R.drawable.flag_cz, "CZK", "Kč"),
    Country("DE", "Germany", "+49", R.drawable.flag_de, "EUR", "€"),
    Country("DJ", "Djibouti", "+253", R.drawable.flag_dj, "DJF", "‎Fdj"),
    Country("DK", "Denmark", "+45", R.drawable.flag_dk, "DKK", "kr"),
    Country("DM", "Dominica", "+1", R.drawable.flag_dm, "XCD", "$"),
    Country("DO", "Dominican Republic", "+1", R.drawable.flag_do, "DOP", "RD$"),
    Country("DZ", "Algeria", "+213", R.drawable.flag_dz, "DZD", "‎دج"),
    Country("EC", "Ecuador", "+593", R.drawable.flag_ec, "USD", "$"),
    Country("EE", "Estonia", "+372", R.drawable.flag_ee, "EUR", "€"),
    Country("EG", "Egypt", "+20", R.drawable.flag_eg, "EGP", "£"),
    Country("EH", "Western Sahara", "+212", R.drawable.flag_eh, "MAD", "MAD"),
    Country("ER", "Eritrea", "+291", R.drawable.flag_er, "ERN", "‎Nfk"),
    Country("ES", "Spain", "+34", R.drawable.flag_es, "EUR", "€"),
    Country("ET", "Ethiopia", "+251", R.drawable.flag_et, "ETB", "Br"),
    Country("FI", "Finland", "+358", R.drawable.flag_fi, "EUR", "€"),
    Country("FJ", "Fiji", "+679", R.drawable.flag_fj, "FJD", "‎FJ$"),
    Country("FK", "Falkland Islands (Malvinas)", "+500", R.drawable.flag_fk, "FKP", "‎FKP"),
    Country("FM", "Micronesia, Federated States of", "+691", R.drawable.flag_fm, "USD", "$"),
    Country("FO", "Faroe Islands", "+298", R.drawable.flag_fo, "DKK", "kr"),
    Country("FR", "France", "+33", R.drawable.flag_fr, "EUR", "€"),
    Country("GA", "Gabon", "+241", R.drawable.flag_ga, "XAF", "FCFA"),
    Country("GB", "United Kingdom", "+44", R.drawable.flag_gb, "GBP", "£"),
    Country("GD", "Grenada", "+1", R.drawable.flag_gd, "XCD", "$"),
    Country("GE", "Georgia", "+995", R.drawable.flag_ge, "GEL", "₾"),
    Country("GF", "French Guiana", "+594", R.drawable.flag_gf, "EUR", "€"),
    Country("GG", "Guernsey", "+44", R.drawable.flag_gg, "GGP", "‎£"),
    Country("GH", "Ghana", "+233", R.drawable.flag_gh, "GHS", "¢"),
    Country("GI", "Gibraltar", "+350", R.drawable.flag_gi, "GIP", "‎£"),
    Country("GL", "Greenland", "+299", R.drawable.flag_gl, "DKK", "kr"),
    Country("GM", "Gambia", "+220", R.drawable.flag_gm, "GMD", "D"),
    Country("GN", "Guinea", "+224", R.drawable.flag_gn, "GNF", "FG"),
    Country("GP", "Guadeloupe", "+590", R.drawable.flag_gp, "EUR", "€"),
    Country("GQ", "Equatorial Guinea", "+240", R.drawable.flag_gq, "XAF", "FCFA"),
    Country("GR", "Greece", "+30", R.drawable.flag_gr, "EUR", "€"),
    Country(
        "GS", "South Georgia and the South Sandwich Islands", "+500", R.drawable.flag_gs,
        "GBP", "£"
    ),
    Country("GT", "Guatemala", "+502", R.drawable.flag_gt, "GTQ", "‎‎Q"),
    Country("GU", "Guam", "+1", R.drawable.flag_gu, "USD", "$"),
    Country("GW", "Guinea-Bissau", "+245", R.drawable.flag_gw, "XOF", "CFA"),
    Country("GY", "Guyana", "+595", R.drawable.flag_gy, "GYD", "$"),
    Country("HK", "Hong Kong", "+852", R.drawable.flag_hk, "HKD", "$"),
    Country("HM", "Heard Island and McDonald Islands", "+000", R.drawable.flag_hm, "AUD", "AU$"),
    Country("HN", "Honduras", "+504", R.drawable.flag_hn, "HNL", "‎‎L"),
    Country("HR", "Croatia", "+385", R.drawable.flag_hr, "HRK", "kn"),
    Country("HT", "Haiti", "+509", R.drawable.flag_ht, "HTG", "G"),
    Country("HU", "Hungary", "+36", R.drawable.flag_hu, "HUF", "Ft"),
    Country("ID", "Indonesia", "+62", R.drawable.flag_id, "IDR", "Rp"),
    Country("IE", "Ireland", "+353", R.drawable.flag_ie, "EUR", "€"),
    Country("IL", "Israel", "+972", R.drawable.flag_il, "ILS", "₪"),
    Country("IM", "Isle of Man", "+44", R.drawable.flag_im, "GBP", "£"),
    Country("IN", "India", "+91", R.drawable.flag_in, "INR", "₹"),
    Country("IO", "British Indian Ocean Territory", "+246", R.drawable.flag_io, "USD", "$"),
    Country("IQ", "Iraq", "+964", R.drawable.flag_iq, "IQD", "ع.د"),
    Country("IR", "Iran, Islamic Republic of", "+98", R.drawable.flag_ir, "IRR", "﷼"),
    Country("IS", "Iceland", "+354", R.drawable.flag_is, "ISK", "kr"),
    Country("IT", "Italy", "+39", R.drawable.flag_it, "EUR", "€"),
    Country("JE", "Jersey", "+44", R.drawable.flag_je, "JEP", "£"),
    Country("JM", "Jamaica", "+1", R.drawable.flag_jm, "JMD", "J$"),
    Country("JO", "Jordan", "+962", R.drawable.flag_jo, "JOD", "‎د.أ"),
    Country("JP", "Japan", "+81", R.drawable.flag_jp, "JPY", "¥"),
    Country("KE", "Kenya", "+254", R.drawable.flag_ke, "KES", "KSh"),
    Country("KG", "Kyrgyzstan", "+996", R.drawable.flag_kg, "KGS", "Лв"),
    Country("KH", "Cambodia", "+855", R.drawable.flag_kh, "KHR", "៛"),
    Country("KI", "Kiribati", "+686", R.drawable.flag_ki, "AUD", "AU$"),
    Country("KM", "Comoros", "+269", R.drawable.flag_km, "KMF", "CF"),
    Country("KN", "Saint Kitts and Nevis", "+1", R.drawable.flag_kn, "XCD", "$"),
    Country("KP", "North Korea", "+850", R.drawable.flag_kp, "KPW", "₩"),
    Country("KR", "South Korea", "+82", R.drawable.flag_kr, "KRW", "₩"),
    Country("KW", "Kuwait", "+965", R.drawable.flag_kw, "KWD", "د.ك"),
    Country("KY", "Cayman Islands", "+345", R.drawable.flag_ky, "KYD", "$"),
    Country("KZ", "Kazakhstan", "+7", R.drawable.flag_kz, "KZT", "лв"),
    Country("LA", "Lao People's Democratic Republic", "+856", R.drawable.flag_la, "LAK", "₭"),
    Country("LB", "Lebanon", "+961", R.drawable.flag_lb, "LBP", "ل.ل.‎"),
    Country("LC", "Saint Lucia", "+1", R.drawable.flag_lc, "XCD", "$"),
    Country("LI", "Liechtenstein", "+423", R.drawable.flag_li, "CHF", "CHF"),
    Country("LK", "Sri Lanka", "+94", R.drawable.flag_lk, "LKR", "₨"),
    Country("LR", "Liberia", "+231", R.drawable.flag_lr, "LRD", "$"),
    Country("LS", "Lesotho", "+266", R.drawable.flag_ls, "LSL", "‎M"),
    Country("LT", "Lithuania", "+370", R.drawable.flag_lt, "LTL", "Lt"),
    Country("LU", "Luxembourg", "+352", R.drawable.flag_lu, "EUR", "€"),
    Country("LV", "Latvia", "+371", R.drawable.flag_lv, "LVL", "‎Ls"),
    Country("LY", "Libyan Arab Jamahiriya", "+218", R.drawable.flag_ly, "LYD", "‎ل.د"),
    Country("MA", "Morocco", "+212", R.drawable.flag_ma, "MAD", "MAD"),
    Country("MC", "Monaco", "+377", R.drawable.flag_mc, "EUR", "€"),
    Country("MD", "Moldova, Republic of", "+373", R.drawable.flag_md, "MDL", "MDL"),
    Country("ME", "Montenegro", "+382", R.drawable.flag_me, "EUR", "€"),
    Country("MF", "Saint Martin", "+590", R.drawable.flag_mf, "EUR", "€"),
    Country("MG", "Madagascar", "+261", R.drawable.flag_mg, "MGA", "Ar‎"),
    Country("MH", "Marshall Islands", "+692", R.drawable.flag_mh, "USD", "$"),
    Country(
        "MK",
        "Macedonia, The Former Yugoslav Republic of",
        "+389",
        R.drawable.flag_mk,
        "MKD", "ден"
    ),
    Country("ML", "Mali", "+223", R.drawable.flag_ml, "XOF", "CFA"),
    Country("MM", "Myanmar", "+95", R.drawable.flag_mm, "MMK", "K‎"),
    Country("MN", "Mongolia", "+976", R.drawable.flag_mn, "MNT", "₮"),
    Country("MO", "Macao", "+853", R.drawable.flag_mo, "MOP", "MOP$‎"),
    Country("MP", "Northern Mariana Islands", "+1", R.drawable.flag_mp, "USD", "$"),
    Country("MQ", "Martinique", "+596", R.drawable.flag_mq, "EUR", "€"),
    Country("MR", "Mauritania", "+222", R.drawable.flag_mr, "MRO", "UM‎"),
    Country("MS", "Montserrat", "+1", R.drawable.flag_ms, "XCD", "$"),
    Country("MT", "Malta", "+356", R.drawable.flag_mt, "EUR", "€"),
    Country("MU", "Mauritius", "+230", R.drawable.flag_mu, "MUR", "₨"),
    Country("MV", "Maldives", "+960", R.drawable.flag_mv, "MVR", "Rf"),
    Country("MW", "Malawi", "+265", R.drawable.flag_mw, "MWK", "MK"),
    Country("MX", "Mexico", "+52", R.drawable.flag_mx, "MXN", "$"),
    Country("MY", "Malaysia", "+60", R.drawable.flag_my, "MYR", "RM"),
    Country("MZ", "Mozambique", "+258", R.drawable.flag_mz, "MZN", "MT"),
    Country("NA", "Namibia", "+264", R.drawable.flag_na, "NAD", "$"),
    Country("NC", "New Caledonia", "+687", R.drawable.flag_nc, "XPF", "₣"),
    Country("NE", "Niger", "+227", R.drawable.flag_ne, "XOF", "CFA"),
    Country("NF", "Norfolk Island", "+672", R.drawable.flag_nf, "AUD", "AU$"),
    Country("NG", "Nigeria", "+234", R.drawable.flag_ng, "NGN", "₦"),
    Country("NI", "Nicaragua", "+505", R.drawable.flag_ni, "NIO", "C$"),
    Country("NL", "Netherlands", "+31", R.drawable.flag_nl, "EUR", "€"),
    Country("NO", "Norway", "+47", R.drawable.flag_no, "NOK", "kr"),
    Country("NP", "Nepal", "+977", R.drawable.flag_np, "NPR", "रू"),
    Country("NR", "Nauru", "+674", R.drawable.flag_nr, "AUD", "AU$"),
    Country("NU", "Niue", "+683", R.drawable.flag_nu, "NZD", "$"),
    Country("NZ", "New Zealand", "+64", R.drawable.flag_nz, "NZD", "$"),
    Country("OM", "Oman", "+968", R.drawable.flag_om, "OMR", "﷼"),
    Country("PA", "Panama", "+507", R.drawable.flag_pa, "PAB", "B/."),
    Country("PE", "Peru", "+51", R.drawable.flag_pe, "PEN", "S/."),
    Country("PF", "French Polynesia", "+689", R.drawable.flag_pf, "XPF", "₣"),
    Country("PG", "Papua New Guinea", "+675", R.drawable.flag_pg, "PGK", "K"),
    Country("PH", "Philippines", "+63", R.drawable.flag_ph, "PHP", "₱"),
    Country("PK", "Pakistan", "+92", R.drawable.flag_pk, "PKR", "₨"),
    Country("PL", "Poland", "+48", R.drawable.flag_pl, "PLN", "zł"),
    Country("PM", "Saint Pierre and Miquelon", "+508", R.drawable.flag_pm, "EUR", "€"),
    Country("PN", "Pitcairn", "+872", R.drawable.flag_pn, "NZD", "$"),
    Country("PR", "Puerto Rico", "+1", R.drawable.flag_pr, "USD", "$"),
    Country("PS", "Palestinian Territory, Occupied", "+970", R.drawable.flag_ps, "ILS", "₪"),
    Country("PT", "Portugal", "+351", R.drawable.flag_pt, "EUR", "€"),
    Country("PW", "Palau", "+680", R.drawable.flag_pw, "USD", "$"),
    Country("PY", "Paraguay", "+595", R.drawable.flag_py, "PYG", "Gs"),
    Country("QA", "Qatar", "+974", R.drawable.flag_qa, "QAR", "﷼"),
    Country("RE", "Reunion", "+262", R.drawable.flag_re, "EUR", "€"),
    Country("RO", "Romania", "+40", R.drawable.flag_ro, "RON", "lei"),
    Country("RS", "Serbia", "+381", R.drawable.flag_rs, "RSD", "Дин."),
    Country("RU", "Russia", "+7", R.drawable.flag_ru, "RUB", "₽"),
    Country("RW", "Rwanda", "+250", R.drawable.flag_rw, "RWF", "FRw"),
    Country("SA", "Saudi Arabia", "+966", R.drawable.flag_sa, "SAR", "﷼"),
    Country("SB", "Solomon Islands", "+677", R.drawable.flag_sb, "SBD", "Si$"),
    Country("SC", "Seychelles", "+248", R.drawable.flag_sc, "SCR", "SR"),
    Country("SD", "Sudan", "+249", R.drawable.flag_sd, "SDG", "ج.س."),
    Country("SE", "Sweden", "+46", R.drawable.flag_se, "SEK", "kr"),
    Country("SG", "Singapore", "+65", R.drawable.flag_sg, "SGD", "$"),
    Country(
        "SH",
        "Saint Helena, Ascension and Tristan Da Cunha",
        "+290",
        R.drawable.flag_sh,
        "SHP", "£"
    ),
    Country("SI", "Slovenia", "+386", R.drawable.flag_si, "EUR", "€"),
    Country("SJ", "Svalbard and Jan Mayen", "+47", R.drawable.flag_sj, "NOK", "kr"),
    Country("SK", "Slovakia", "+421", R.drawable.flag_sk, "EUR", "€"),
    Country("SL", "Sierra Leone", "+232", R.drawable.flag_sl, "SLL", "Le"),
    Country("SM", "San Marino", "+378", R.drawable.flag_sm, "EUR", "€"),
    Country("SN", "Senegal", "+221", R.drawable.flag_sn, "XOF", "CFA"),
    Country("SO", "Somalia", "+252", R.drawable.flag_so, "SOS", "S"),
    Country("SR", "Suriname", "+597", R.drawable.flag_sr, "SRD", "$"),
    Country("SS", "South Sudan", "+211", R.drawable.flag_ss, "SSP", "SS£"),
    Country("ST", "Sao Tome and Principe", "+239", R.drawable.flag_st, "STD", "Db"),
    Country("SV", "El Salvador", "+503", R.drawable.flag_sv, "SVC", "₡"),
    Country("SX", "Sint Maarten", "+1", R.drawable.flag_sx, "ANG", "ƒ "),
    Country("SY", "Syrian Arab Republic", "+963", R.drawable.flag_sy, "SYP", "£"),
    Country("SZ", "Swaziland", "+268", R.drawable.flag_sz, "SZL", "E"),
    Country("TC", "Turks and Caicos Islands", "+1", R.drawable.flag_tc, "USD", "$"),
    Country("TD", "Chad", "+235", R.drawable.flag_td, "XAF", "FCFA"),
    Country("TF", "French Southern Territories", "+262", R.drawable.flag_tf, "EUR", "€"),
    Country("TG", "Togo", "+228", R.drawable.flag_tg, "XOF", "CFA"),
    Country("TH", "Thailand", "+66", R.drawable.flag_th, "THB", "฿"),
    Country("TJ", "Tajikistan", "+992", R.drawable.flag_tj, "TJS", "ЅM"),
    Country("TK", "Tokelau", "+690", R.drawable.flag_tk, "NZD", "$"),
    Country("TL", "East Timor", "+670", R.drawable.flag_tl, "USD", "$"),
    Country("TM", "Turkmenistan", "+993", R.drawable.flag_tm, "TMT", "T"),
    Country("TN", "Tunisia", "+216", R.drawable.flag_tn, "TND", "TD"),
    Country("TO", "Tonga", "+676", R.drawable.flag_to, "TOP", "T$"),
    Country("TR", "Turkey", "+90", R.drawable.flag_tr, "TRY", "₺"),
    Country("TT", "Trinidad and Tobago", "+1", R.drawable.flag_tt, "TTD", "TT$"),
    Country("TV", "Tuvalu", "+688", R.drawable.flag_tv, "AUD", "AU$"),
    Country("TW", "Taiwan", "+886", R.drawable.flag_tw, "TWD", "NT$"),
    Country("TZ", "Tanzania, United Republic of", "+255", R.drawable.flag_tz, "TZS", "TSh"),
    Country("UA", "Ukraine", "+380", R.drawable.flag_ua, "UAH", "₴"),
    Country("UG", "Uganda", "+256", R.drawable.flag_ug, "UGX", "USh"),
    Country("UM", "U.S. Minor Outlying Islands", "+1", R.drawable.flag_um, "USD", "$"),
    Country("US", "United States", "+1", R.drawable.flag_us, "USD", "$"),
    Country("UY", "Uruguay", "+598", R.drawable.flag_uy, "UYU", "${'$'}U"),
    Country("UZ", "Uzbekistan", "+998", R.drawable.flag_uz, "UZS", "so'm"),
    Country("VA", "Holy See (Vatican City State)", "+379", R.drawable.flag_va, "EUR", "€"),
    Country("VC", "Saint Vincent and the Grenadines", "+1", R.drawable.flag_vc, "XCD", "$"),
    Country("VE", "Venezuela, Bolivarian Republic of", "+58", R.drawable.flag_ve, "VEF", "Bs"),
    Country("VG", "Virgin Islands, British", "+1", R.drawable.flag_vg, "USD", "$"),
    Country("VI", "Virgin Islands, U.S.", "+1", R.drawable.flag_vi, "USD", "$"),
    Country("VN", "Vietnam", "+84", R.drawable.flag_vn, "VND", "₫"),
    Country("VU", "Vanuatu", "+678", R.drawable.flag_vu, "VUV", "Vt"),
    Country("WF", "Wallis and Futuna", "+681", R.drawable.flag_wf, "XPF", "₣"),
    Country("WS", "Samoa", "+685", R.drawable.flag_ws, "WST", "WS$"),
    Country("XK", "Kosovo", "+383", R.drawable.flag_xk, "EUR", "€"),
    Country("YE", "Yemen", "+967", R.drawable.flag_ye, "YER", "﷼"),
    Country("YT", "Mayotte", "+262", R.drawable.flag_yt, "EUR", "€"),
    Country("ZA", "South Africa", "+27", R.drawable.flag_za, "ZAR", "R"),
    Country("ZM", "Zambia", "+260", R.drawable.flag_zm, "ZMW", "ZK"),
    Country("ZW", "Zimbabwe", "+263", R.drawable.flag_zw, "USD", "$")
)

data class Country(
    val code: String,
    val name: String,
    val dialCode: String,
    val flag: Int,
    val currency: String,
    val currencySymbol: String
)


fun getAllCountriesAndCurrencies(): ArrayList<Country> {
    val list = arrayListOf<Country>()
    list.addAll(COUNTRIES)
    return list
}