package com.priyank.countrypicker

internal object Countries {

    val COUNTRIES = arrayOf(
        CountryPicker.CountryModel(
            "AD",
            R.string.andorra,
            "+376",
            R.drawable.flag_ad,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "AE", R.string.united_arab_emirates,
            "+971",
            R.drawable.flag_ae,
            "AED",
            "د.إ"
        ),
        CountryPicker.CountryModel(
            "AF",
            R.string.afghanistan,
            "+93",
            R.drawable.flag_af,
            "AFN",
            "؋"
        ),
        CountryPicker.CountryModel(
            "AG",
            R.string.antigua_and_barbuda,
            "+1",
            R.drawable.flag_ag,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "AI",
            R.string.anguilla,
            "+1",
            R.drawable.flag_ai,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "AL",
            R.string.albania,
            "+355",
            R.drawable.flag_al,
            "ALL",
            "L"
        ),
        CountryPicker.CountryModel(
            "AM",
            R.string.armenia,
            "+374",
            R.drawable.flag_am,
            "AMD",
            "֏"
        ),
        CountryPicker.CountryModel(
            "AO",
            R.string.angola,
            "+244",
            R.drawable.flag_ao,
            "AOA",
            "Kz"
        ),
        CountryPicker.CountryModel(
            "AQ",
            R.string.antarctica,
            "+672",
            R.drawable.flag_aq,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "AR",
            R.string.argentina,
            "+54",
            R.drawable.flag_ar,
            "ARS",
            "$"
        ),
        CountryPicker.CountryModel(
            "AS",
            R.string.american_samoa,
            "+1",
            R.drawable.flag_as,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "AT",
            R.string.austria,
            "+43",
            R.drawable.flag_at,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "AU",
            R.string.australia,
            "+61",
            R.drawable.flag_au,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "AW",
            R.string.aruba,
            "+297",
            R.drawable.flag_aw,
            "AWG",
            "Afl"
        ),
        CountryPicker.CountryModel(
            "AX",
            R.string.aland_islands,
            "+358",
            R.drawable.flag_ax,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "AZ",
            R.string.azerbaijan,
            "+994",
            R.drawable.flag_az,
            "AZN",
            "₼"
        ),
        CountryPicker.CountryModel(
            "BA",
            R.string.bosnia_and_herzegovina,
            "+387",
            R.drawable.flag_ba,
            "BAM",
            "KM"
        ),
        CountryPicker.CountryModel(
            "BB",
            R.string.barbados,
            "+1",
            R.drawable.flag_bb,
            "BBD",
            "$"
        ),
        CountryPicker.CountryModel(
            "BD",
            R.string.bangladesh,
            "+880",
            R.drawable.flag_bd,
            "BDT",
            " Tk"
        ),
        CountryPicker.CountryModel(
            "BE",
            R.string.belgium,
            "+32",
            R.drawable.flag_be,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "BF",
            R.string.burkina_faso,
            "+226",
            R.drawable.flag_bf,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "BG",
            R.string.bulgaria,
            "+359",
            R.drawable.flag_bg,
            "BGN",
            "лв"
        ),
        CountryPicker.CountryModel(
            "BH",
            R.string.bahrain,
            "+973",
            R.drawable.flag_bh,
            "BHD",
            "BD"
        ),
        CountryPicker.CountryModel(
            "BI",
            R.string.burundi,
            "+257",
            R.drawable.flag_bi,
            "BIF",
            "FBu"
        ),
        CountryPicker.CountryModel(
            "BJ",
            R.string.benin,
            "+229",
            R.drawable.flag_bj,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "BL",
            R.string.saint_barthelemy,
            "+590",
            R.drawable.flag_bl,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "BM",
            R.string.bermuda,
            "+1",
            R.drawable.flag_bm,
            "BMD",
            "$"
        ),
        CountryPicker.CountryModel(
            "BN",
            R.string.brunei_darussalam,
            "+673",
            R.drawable.flag_bn,
            "BND",
            "$"
        ),
        CountryPicker.CountryModel(
            "BO",
            R.string.bolivia_plurinational_state_of,
            "+591",
            R.drawable.flag_bo,
            "BOB",
            "${'$'}b"
        ),
        CountryPicker.CountryModel(
            "BQ",
            R.string.bonaire,
            "+599",
            R.drawable.flag_bq,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "BR",
            R.string.brazil,
            "+55",
            R.drawable.flag_br,
            "BRL",
            "R$"
        ),
        CountryPicker.CountryModel(
            "BS",
            R.string.bahamas,
            "+1",
            R.drawable.flag_bs,
            "BSD",
            "$"
        ),
        CountryPicker.CountryModel(
            "BT",
            R.string.bhutan,
            "+975",
            R.drawable.flag_bt,
            "BTN",
            "Nu."
        ),
        CountryPicker.CountryModel(
            "BV",
            R.string.bouvet_island,
            "+47",
            R.drawable.flag_bv,
            "NOK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "BW",
            R.string.botswana,
            "+267",
            R.drawable.flag_bw,
            "BWP",
            "P"
        ),
        CountryPicker.CountryModel(
            "BY",
            R.string.belarus,
            "+375",
            R.drawable.flag_by,
            "BYR",
            "br"
        ),
        CountryPicker.CountryModel(
            "BZ",
            R.string.belize,
            "+501",
            R.drawable.flag_bz,
            "BZD",
            "BZ$"
        ),
        CountryPicker.CountryModel(
            "CA",
            R.string.canada,
            "+1",
            R.drawable.flag_ca,
            "CAD",
            "$"
        ),
        CountryPicker.CountryModel(
            "CC",
            R.string.cocos_keeling_islands,
            "+61",
            R.drawable.flag_cc,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "CD",
            R.string.congo_the_democratic_republic_of_the,
            "+243",
            R.drawable.flag_cd,
            "CDF",
            "FC"
        ),
        CountryPicker.CountryModel(
            "CF",
            R.string.central_african_republic,
            "+236",
            R.drawable.flag_cf,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "CG",
            R.string.congo,
            "+242",
            R.drawable.flag_cg,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "CH",
            R.string.switzerland,
            "+41",
            R.drawable.flag_ch,
            "CHF",
            "CHF"
        ),
        CountryPicker.CountryModel(
            "CI",
            R.string.ivory_coast,
            "+225",
            R.drawable.flag_ci,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "CK",
            R.string.cook_islands,
            "+682",
            R.drawable.flag_ck,
            "NZD",
            "$"
        ),
        CountryPicker.CountryModel(
            "CL",
            R.string.chile,
            "+56",
            R.drawable.flag_cl,
            "CLP",
            "$"
        ),
        CountryPicker.CountryModel(
            "CM",
            R.string.cameroon,
            "+237",
            R.drawable.flag_cm,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "CN",
            R.string.china,
            "+86",
            R.drawable.flag_cn,
            "CNY",
            "¥"
        ),
        CountryPicker.CountryModel(
            "CO",
            R.string.colombia,
            "+57",
            R.drawable.flag_co,
            "COP",
            "$"
        ),
        CountryPicker.CountryModel(
            "CR",
            R.string.costa_rica,
            "+506",
            R.drawable.flag_cr,
            "CRC",
            "₡"
        ),
        CountryPicker.CountryModel(
            "CU",
            R.string.cuba,
            "+53",
            R.drawable.flag_cu,
            "CUP",
            "$"
        ),
        CountryPicker.CountryModel(
            "CV",
            R.string.cape_verde,
            "+238",
            R.drawable.flag_cv,
            "CVE",
            "$"
        ),
        CountryPicker.CountryModel(
            "CW",
            R.string.curacao,
            "+599",
            R.drawable.flag_cw,
            "ANG",
            "ƒ "
        ),
        CountryPicker.CountryModel(
            "CX",
            R.string.christmas_island,
            "+61",
            R.drawable.flag_cx,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "CY",
            R.string.cyprus,
            "+357",
            R.drawable.flag_cy,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "CZ",
            R.string.czech_republic,
            "+420",
            R.drawable.flag_cz,
            "CZK",
            "Kč"
        ),
        CountryPicker.CountryModel(
            "DE",
            R.string.germany,
            "+49",
            R.drawable.flag_de,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "DJ",
            R.string.djibouti,
            "+253",
            R.drawable.flag_dj,
            "DJF",
            "‎Fdj"
        ),
        CountryPicker.CountryModel(
            "DK",
            R.string.denmark,
            "+45",
            R.drawable.flag_dk,
            "DKK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "DM",
            R.string.dominica,
            "+1",
            R.drawable.flag_dm,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "DO",
            R.string.dominican_republic,
            "+1",
            R.drawable.flag_do,
            "DOP",
            "RD$"
        ),
        CountryPicker.CountryModel(
            "DZ",
            R.string.algeria,
            "+213",
            R.drawable.flag_dz,
            "DZD",
            "‎دج"
        ),
        CountryPicker.CountryModel(
            "EC",
            R.string.ecuador,
            "+593",
            R.drawable.flag_ec,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "EE",
            R.string.estonia,
            "+372",
            R.drawable.flag_ee,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "EG",
            R.string.egypt,
            "+20",
            R.drawable.flag_eg,
            "EGP",
            "£"
        ),
        CountryPicker.CountryModel(
            "EH",
            R.string.western_sahara,
            "+212",
            R.drawable.flag_eh,
            "MAD",
            "MAD"
        ),
        CountryPicker.CountryModel(
            "ER",
            R.string.eritrea,
            "+291",
            R.drawable.flag_er,
            "ERN",
            "‎Nfk"
        ),
        CountryPicker.CountryModel(
            "ES",
            R.string.spain,
            "+34",
            R.drawable.flag_es,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "ET",
            R.string.ethiopia,
            "+251",
            R.drawable.flag_et,
            "ETB",
            "Br"
        ),
        CountryPicker.CountryModel(
            "FI",
            R.string.finland,
            "+358",
            R.drawable.flag_fi,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "FJ",
            R.string.fiji,
            "+679",
            R.drawable.flag_fj,
            "FJD",
            "‎FJ$"
        ),
        CountryPicker.CountryModel(
            "FK",
            R.string.falkland_islands_malvinas,
            "+500",
            R.drawable.flag_fk,
            "FKP",
            "‎FKP"
        ),
        CountryPicker.CountryModel(
            "FM",
            R.string.micronesia_federated_states_of,
            "+691",
            R.drawable.flag_fm,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "FO",
            R.string.faroe_islands,
            "+298",
            R.drawable.flag_fo,
            "DKK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "FR",
            R.string.france,
            "+33",
            R.drawable.flag_fr,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "GA",
            R.string.gabon,
            "+241",
            R.drawable.flag_ga,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "GB",
            R.string.united_kingdom,
            "+44",
            R.drawable.flag_gb,
            "GBP",
            "£"
        ),
        CountryPicker.CountryModel(
            "GD",
            R.string.grenada,
            "+1",
            R.drawable.flag_gd,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "GE",
            R.string.georgia,
            "+995",
            R.drawable.flag_ge,
            "GEL",
            "₾"
        ),
        CountryPicker.CountryModel(
            "GF",
            R.string.french_guiana,
            "+594",
            R.drawable.flag_gf,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "GG",
            R.string.guernsey,
            "+44",
            R.drawable.flag_gg,
            "GGP",
            "‎£"
        ),
        CountryPicker.CountryModel(
            "GH",
            R.string.ghana,
            "+233",
            R.drawable.flag_gh,
            "GHS",
            "¢"
        ),
        CountryPicker.CountryModel(
            "GI",
            R.string.gibraltar,
            "+350",
            R.drawable.flag_gi,
            "GIP",
            "‎£"
        ),
        CountryPicker.CountryModel(
            "GL",
            R.string.greenland,
            "+299",
            R.drawable.flag_gl,
            "DKK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "GM",
            R.string.gambia,
            "+220",
            R.drawable.flag_gm,
            "GMD",
            "D"
        ),
        CountryPicker.CountryModel(
            "GN",
            R.string.guinea,
            "+224",
            R.drawable.flag_gn,
            "GNF",
            "FG"
        ),
        CountryPicker.CountryModel(
            "GP",
            R.string.guadeloupe,
            "+590",
            R.drawable.flag_gp,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "GQ",
            R.string.equatorial_guinea,
            "+240",
            R.drawable.flag_gq,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "GR",
            R.string.greece,
            "+30",
            R.drawable.flag_gr,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "GS",
            R.string.south_georgia_and_the_south_sandwich_islands,
            "+500",
            R.drawable.flag_gs,
            "GBP",
            "£"
        ),
        CountryPicker.CountryModel(
            "GT",
            R.string.guatemala,
            "+502",
            R.drawable.flag_gt,
            "GTQ",
            "‎‎Q"
        ),
        CountryPicker.CountryModel(
            "GU",
            R.string.guam,
            "+1",
            R.drawable.flag_gu,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "GW",
            R.string.guinea_bissau,
            "+245",
            R.drawable.flag_gw,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "GY",
            R.string.guyana,
            "+595",
            R.drawable.flag_gy,
            "GYD",
            "$"
        ),
        CountryPicker.CountryModel(
            "HK",
            R.string.hong_kong,
            "+852",
            R.drawable.flag_hk,
            "HKD",
            "$"
        ),
        CountryPicker.CountryModel(
            "HM",
            R.string.heard_island_and_mcdonald_islands,
            "+000",
            R.drawable.flag_hm,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "HN",
            R.string.honduras,
            "+504",
            R.drawable.flag_hn,
            "HNL",
            "‎‎L"
        ),
        CountryPicker.CountryModel(
            "HR",
            R.string.croatia,
            "+385",
            R.drawable.flag_hr,
            "HRK",
            "kn"
        ),
        CountryPicker.CountryModel(
            "HT",
            R.string.haiti,
            "+509",
            R.drawable.flag_ht,
            "HTG",
            "G"
        ),
        CountryPicker.CountryModel(
            "HU",
            R.string.hungary,
            "+36",
            R.drawable.flag_hu,
            "HUF",
            "Ft"
        ),
        CountryPicker.CountryModel(
            "ID",
            R.string.indonesia,
            "+62",
            R.drawable.flag_id,
            "IDR",
            "Rp"
        ),
        CountryPicker.CountryModel(
            "IE",
            R.string.ireland,
            "+353",
            R.drawable.flag_ie,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "IL",
            R.string.israel,
            "+972",
            R.drawable.flag_il,
            "ILS",
            "₪"
        ),
        CountryPicker.CountryModel(
            "IM",
            R.string.isle_of_man,
            "+44",
            R.drawable.flag_im,
            "GBP",
            "£"
        ),
        CountryPicker.CountryModel(
            "IN",
            R.string.india,
            "+91",
            R.drawable.flag_in,
            "INR",
            "₹"
        ),
        CountryPicker.CountryModel(
            "IO",
            R.string.british_indian_ocean_territory,
            "+246",
            R.drawable.flag_io,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "IQ",
            R.string.iraq,
            "+964",
            R.drawable.flag_iq,
            "IQD",
            "ع.د"
        ),
        CountryPicker.CountryModel(
            "IR",
            R.string.iran_islamic_republic_of,
            "+98",
            R.drawable.flag_ir,
            "IRR",
            "﷼"
        ),
        CountryPicker.CountryModel(
            "IS",
            R.string.iceland,
            "+354",
            R.drawable.flag_is,
            "ISK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "IT",
            R.string.italy,
            "+39",
            R.drawable.flag_it,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "JE",
            R.string.jersey,
            "+44",
            R.drawable.flag_je,
            "JEP",
            "£"
        ),
        CountryPicker.CountryModel(
            "JM",
            R.string.jamaica,
            "+1",
            R.drawable.flag_jm,
            "JMD",
            "J$"
        ),
        CountryPicker.CountryModel(
            "JO",
            R.string.jordan,
            "+962",
            R.drawable.flag_jo,
            "JOD",
            "‎د.أ"
        ),
        CountryPicker.CountryModel(
            "JP",
            R.string.japan,
            "+81",
            R.drawable.flag_jp,
            "JPY",
            "¥"
        ),
        CountryPicker.CountryModel(
            "KE",
            R.string.kenya,
            "+254",
            R.drawable.flag_ke,
            "KES",
            "KSh"
        ),
        CountryPicker.CountryModel(
            "KG",
            R.string.kyrgyzstan,
            "+996",
            R.drawable.flag_kg,
            "KGS",
            "Лв"
        ),
        CountryPicker.CountryModel(
            "KH",
            R.string.cambodia,
            "+855",
            R.drawable.flag_kh,
            "KHR",
            "៛"
        ),
        CountryPicker.CountryModel(
            "KI",
            R.string.kiribati,
            "+686",
            R.drawable.flag_ki,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "KM",
            R.string.comoros,
            "+269",
            R.drawable.flag_km,
            "KMF",
            "CF"
        ),
        CountryPicker.CountryModel(
            "KN",
            R.string.saint_kitts_and_nevis,
            "+1",
            R.drawable.flag_kn,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "KP",
            R.string.north_korea,
            "+850",
            R.drawable.flag_kp,
            "KPW",
            "₩"
        ),
        CountryPicker.CountryModel(
            "KR",
            R.string.south_korea,
            "+82",
            R.drawable.flag_kr,
            "KRW",
            "₩"
        ),
        CountryPicker.CountryModel(
            "KW",
            R.string.kuwait,
            "+965",
            R.drawable.flag_kw,
            "KWD",
            "د.ك"
        ),
        CountryPicker.CountryModel(
            "KY",
            R.string.cayman_islands,
            "+345",
            R.drawable.flag_ky,
            "KYD",
            "$"
        ),
        CountryPicker.CountryModel(
            "KZ",
            R.string.kazakhstan,
            "+7",
            R.drawable.flag_kz,
            "KZT",
            "лв"
        ),
        CountryPicker.CountryModel(
            "LA",
            R.string.lao_people_s_democratic_republic,
            "+856",
            R.drawable.flag_la,
            "LAK",
            "₭"
        ),
        CountryPicker.CountryModel(
            "LB",
            R.string.lebanon,
            "+961",
            R.drawable.flag_lb,
            "LBP",
            "ل.ل.‎"
        ),
        CountryPicker.CountryModel(
            "LC",
            R.string.saint_lucia,
            "+1",
            R.drawable.flag_lc,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "LI",
            R.string.liechtenstein,
            "+423",
            R.drawable.flag_li,
            "CHF",
            "CHF"
        ),
        CountryPicker.CountryModel(
            "LK",
            R.string.sri_lanka,
            "+94",
            R.drawable.flag_lk,
            "LKR",
            "₨"
        ),
        CountryPicker.CountryModel(
            "LR",
            R.string.liberia,
            "+231",
            R.drawable.flag_lr,
            "LRD",
            "$"
        ),
        CountryPicker.CountryModel(
            "LS",
            R.string.lesotho,
            "+266",
            R.drawable.flag_ls,
            "LSL",
            "‎M"
        ),
        CountryPicker.CountryModel(
            "LT",
            R.string.lithuania,
            "+370",
            R.drawable.flag_lt,
            "LTL",
            "Lt"
        ),
        CountryPicker.CountryModel(
            "LU",
            R.string.luxembourg,
            "+352",
            R.drawable.flag_lu,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "LV",
            R.string.latvia,
            "+371",
            R.drawable.flag_lv,
            "LVL",
            "‎Ls"
        ),
        CountryPicker.CountryModel(
            "LY",
            R.string.libyan_arab_jamahiriya,
            "+218",
            R.drawable.flag_ly,
            "LYD",
            "‎ل.د"
        ),
        CountryPicker.CountryModel(
            "MA",
            R.string.morocco,
            "+212",
            R.drawable.flag_ma,
            "MAD",
            "MAD"
        ),
        CountryPicker.CountryModel(
            "MC",
            R.string.monaco,
            "+377",
            R.drawable.flag_mc,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "MD",
            R.string.moldova_republic_of,
            "+373",
            R.drawable.flag_md,
            "MDL",
            "MDL"
        ),
        CountryPicker.CountryModel(
            "ME",
            R.string.montenegro,
            "+382",
            R.drawable.flag_me,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "MF",
            R.string.saint_martin,
            "+590",
            R.drawable.flag_mf,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "MG",
            R.string.madagascar,
            "+261",
            R.drawable.flag_mg,
            "MGA",
            "Ar‎"
        ),
        CountryPicker.CountryModel(
            "MH",
            R.string.marshall_islands,
            "+692",
            R.drawable.flag_mh,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "MK",
            R.string.macedonia_the_former_yugoslav_republic_of,
            "+389",
            R.drawable.flag_mk,
            "MKD",
            "ден"
        ),
        CountryPicker.CountryModel(
            "ML",
            R.string.mali,
            "+223",
            R.drawable.flag_ml,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "MM",
            R.string.myanmar,
            "+95",
            R.drawable.flag_mm,
            "MMK",
            "K‎"
        ),
        CountryPicker.CountryModel(
            "MN",
            R.string.mongolia,
            "+976",
            R.drawable.flag_mn,
            "MNT",
            "₮"
        ),
        CountryPicker.CountryModel(
            "MO",
            R.string.macao,
            "+853",
            R.drawable.flag_mo,
            "MOP",
            "MOP$‎"
        ),
        CountryPicker.CountryModel(
            "MP",
            R.string.northern_mariana_islands,
            "+1",
            R.drawable.flag_mp,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "MQ",
            R.string.martinique,
            "+596",
            R.drawable.flag_mq,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "MR",
            R.string.mauritania,
            "+222",
            R.drawable.flag_mr,
            "MRO",
            "UM‎"
        ),
        CountryPicker.CountryModel(
            "MS",
            R.string.montserrat,
            "+1",
            R.drawable.flag_ms,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "MT",
            R.string.malta,
            "+356",
            R.drawable.flag_mt,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "MU",
            R.string.mauritius,
            "+230",
            R.drawable.flag_mu,
            "MUR",
            "₨"
        ),
        CountryPicker.CountryModel(
            "MV",
            R.string.maldives,
            "+960",
            R.drawable.flag_mv,
            "MVR",
            "Rf"
        ),
        CountryPicker.CountryModel(
            "MW",
            R.string.malawi,
            "+265",
            R.drawable.flag_mw,
            "MWK",
            "MK"
        ),
        CountryPicker.CountryModel(
            "MX",
            R.string.mexico,
            "+52",
            R.drawable.flag_mx,
            "MXN",
            "$"
        ),
        CountryPicker.CountryModel(
            "MY",
            R.string.malaysia,
            "+60",
            R.drawable.flag_my,
            "MYR",
            "RM"
        ),
        CountryPicker.CountryModel(
            "MZ",
            R.string.mozambique,
            "+258",
            R.drawable.flag_mz,
            "MZN",
            "MT"
        ),
        CountryPicker.CountryModel(
            "NA",
            R.string.namibia,
            "+264",
            R.drawable.flag_na,
            "NAD",
            "$"
        ),
        CountryPicker.CountryModel(
            "NC",
            R.string.new_caledonia,
            "+687",
            R.drawable.flag_nc,
            "XPF",
            "₣"
        ),
        CountryPicker.CountryModel(
            "NE",
            R.string.niger,
            "+227",
            R.drawable.flag_ne,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "NF",
            R.string.norfolk_island,
            "+672",
            R.drawable.flag_nf,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "NG",
            R.string.nigeria,
            "+234",
            R.drawable.flag_ng,
            "NGN",
            "₦"
        ),
        CountryPicker.CountryModel(
            "NI",
            R.string.nicaragua,
            "+505",
            R.drawable.flag_ni,
            "NIO",
            "C$"
        ),
        CountryPicker.CountryModel(
            "NL",
            R.string.netherlands,
            "+31",
            R.drawable.flag_nl,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "NO",
            R.string.norway,
            "+47",
            R.drawable.flag_no,
            "NOK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "NP",
            R.string.nepal,
            "+977",
            R.drawable.flag_np,
            "NPR",
            "रू"
        ),
        CountryPicker.CountryModel(
            "NR",
            R.string.nauru,
            "+674",
            R.drawable.flag_nr,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "NU",
            R.string.niue,
            "+683",
            R.drawable.flag_nu,
            "NZD",
            "$"
        ),
        CountryPicker.CountryModel(
            "NZ",
            R.string.new_zealand,
            "+64",
            R.drawable.flag_nz,
            "NZD",
            "$"
        ),
        CountryPicker.CountryModel(
            "OM",
            R.string.oman,
            "+968",
            R.drawable.flag_om,
            "OMR",
            "﷼"
        ),
        CountryPicker.CountryModel(
            "PA",
            R.string.panama,
            "+507",
            R.drawable.flag_pa,
            "PAB",
            "B/."
        ),
        CountryPicker.CountryModel(
            "PE",
            R.string.peru,
            "+51",
            R.drawable.flag_pe,
            "PEN",
            "S/."
        ),
        CountryPicker.CountryModel(
            "PF",
            R.string.french_polynesia,
            "+689",
            R.drawable.flag_pf,
            "XPF",
            "₣"
        ),
        CountryPicker.CountryModel(
            "PG",
            R.string.papua_new_guinea,
            "+675",
            R.drawable.flag_pg,
            "PGK",
            "K"
        ),
        CountryPicker.CountryModel(
            "PH",
            R.string.philippines,
            "+63",
            R.drawable.flag_ph,
            "PHP",
            "₱"
        ),
        CountryPicker.CountryModel(
            "PK",
            R.string.pakistan,
            "+92",
            R.drawable.flag_pk,
            "PKR",
            "₨"
        ),
        CountryPicker.CountryModel(
            "PL",
            R.string.poland,
            "+48",
            R.drawable.flag_pl,
            "PLN",
            "zł"
        ),
        CountryPicker.CountryModel(
            "PM",
            R.string.saint_pierre_and_miquelon,
            "+508",
            R.drawable.flag_pm,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "PN",
            R.string.pitcairn,
            "+872",
            R.drawable.flag_pn,
            "NZD",
            "$"
        ),
        CountryPicker.CountryModel(
            "PR",
            R.string.puerto_rico,
            "+1",
            R.drawable.flag_pr,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "PS",
            R.string.palestinian_territory_occupied,
            "+970",
            R.drawable.flag_ps,
            "ILS",
            "₪"
        ),
        CountryPicker.CountryModel(
            "PT",
            R.string.portugal,
            "+351",
            R.drawable.flag_pt,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "PW",
            R.string.palau,
            "+680",
            R.drawable.flag_pw,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "PY",
            R.string.paraguay,
            "+595",
            R.drawable.flag_py,
            "PYG",
            "Gs"
        ),
        CountryPicker.CountryModel(
            "QA",
            R.string.qatar,
            "+974",
            R.drawable.flag_qa,
            "QAR",
            "﷼"
        ),
        CountryPicker.CountryModel(
            "RE",
            R.string.reunion,
            "+262",
            R.drawable.flag_re,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "RO",
            R.string.romania,
            "+40",
            R.drawable.flag_ro,
            "RON",
            "lei"
        ),
        CountryPicker.CountryModel(
            "RS",
            R.string.serbia,
            "+381",
            R.drawable.flag_rs,
            "RSD",
            "Дин."
        ),
        CountryPicker.CountryModel(
            "RU",
            R.string.russia,
            "+7",
            R.drawable.flag_ru,
            "RUB",
            "₽"
        ),
        CountryPicker.CountryModel(
            "RW",
            R.string.rwanda,
            "+250",
            R.drawable.flag_rw,
            "RWF",
            "FRw"
        ),
        CountryPicker.CountryModel(
            "SA",
            R.string.saudi_arabia,
            "+966",
            R.drawable.flag_sa,
            "SAR",
            "﷼"
        ),
        CountryPicker.CountryModel(
            "SB",
            R.string.solomon_islands,
            "+677",
            R.drawable.flag_sb,
            "SBD",
            "Si$"
        ),
        CountryPicker.CountryModel(
            "SC",
            R.string.seychelles,
            "+248",
            R.drawable.flag_sc,
            "SCR",
            "SR"
        ),
        CountryPicker.CountryModel(
            "SD",
            R.string.sudan,
            "+249",
            R.drawable.flag_sd,
            "SDG",
            "ج.س."
        ),
        CountryPicker.CountryModel(
            "SE",
            R.string.sweden,
            "+46",
            R.drawable.flag_se,
            "SEK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "SG",
            R.string.singapore,
            "+65",
            R.drawable.flag_sg,
            "SGD",
            "$"
        ),
        CountryPicker.CountryModel(
            "SH",
            R.string.saint_helena_ascension_and_tristan_da_cunha,
            "+290",
            R.drawable.flag_sh,
            "SHP",
            "£"
        ),
        CountryPicker.CountryModel(
            "SI",
            R.string.slovenia,
            "+386",
            R.drawable.flag_si,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "SJ",
            R.string.svalbard_and_jan_mayen,
            "+47",
            R.drawable.flag_sj,
            "NOK",
            "kr"
        ),
        CountryPicker.CountryModel(
            "SK",
            R.string.slovakia,
            "+421",
            R.drawable.flag_sk,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "SL",
            R.string.sierra_leone,
            "+232",
            R.drawable.flag_sl,
            "SLL",
            "Le"
        ),
        CountryPicker.CountryModel(
            "SM",
            R.string.san_marino,
            "+378",
            R.drawable.flag_sm,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "SN",
            R.string.senegal,
            "+221",
            R.drawable.flag_sn,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "SO",
            R.string.somalia,
            "+252",
            R.drawable.flag_so,
            "SOS",
            "S"
        ),
        CountryPicker.CountryModel(
            "SR",
            R.string.suriname,
            "+597",
            R.drawable.flag_sr,
            "SRD",
            "$"
        ),
        CountryPicker.CountryModel(
            "SS",
            R.string.south_sudan,
            "+211",
            R.drawable.flag_ss,
            "SSP",
            "SS£"
        ),
        CountryPicker.CountryModel(
            "ST",
            R.string.sao_tome_and_principe,
            "+239",
            R.drawable.flag_st,
            "STD",
            "Db"
        ),
        CountryPicker.CountryModel(
            "SV",
            R.string.el_salvador,
            "+503",
            R.drawable.flag_sv,
            "SVC",
            "₡"
        ),
        CountryPicker.CountryModel(
            "SX",
            R.string.sint_maarten,
            "+1",
            R.drawable.flag_sx,
            "ANG",
            "ƒ "
        ),
        CountryPicker.CountryModel(
            "SY",
            R.string.syrian_arab_republic,
            "+963",
            R.drawable.flag_sy,
            "SYP",
            "£"
        ),
        CountryPicker.CountryModel(
            "SZ",
            R.string.swaziland,
            "+268",
            R.drawable.flag_sz,
            "SZL",
            "E"
        ),
        CountryPicker.CountryModel(
            "TC",
            R.string.turks_and_caicos_islands,
            "+1",
            R.drawable.flag_tc,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "TD",
            R.string.chad,
            "+235",
            R.drawable.flag_td,
            "XAF",
            "FCFA"
        ),
        CountryPicker.CountryModel(
            "TF",
            R.string.french_southern_territories,
            "+262",
            R.drawable.flag_tf,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "TG",
            R.string.togo,
            "+228",
            R.drawable.flag_tg,
            "XOF",
            "CFA"
        ),
        CountryPicker.CountryModel(
            "TH",
            R.string.thailand,
            "+66",
            R.drawable.flag_th,
            "THB",
            "฿"
        ),
        CountryPicker.CountryModel(
            "TJ",
            R.string.tajikistan,
            "+992",
            R.drawable.flag_tj,
            "TJS",
            "ЅM"
        ),
        CountryPicker.CountryModel(
            "TK",
            R.string.tokelau,
            "+690",
            R.drawable.flag_tk,
            "NZD",
            "$"
        ),
        CountryPicker.CountryModel(
            "TL",
            R.string.east_timor,
            "+670",
            R.drawable.flag_tl,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "TM",
            R.string.turkmenistan,
            "+993",
            R.drawable.flag_tm,
            "TMT",
            "T"
        ),
        CountryPicker.CountryModel(
            "TN",
            R.string.tunisia,
            "+216",
            R.drawable.flag_tn,
            "TND",
            "TD"
        ),
        CountryPicker.CountryModel(
            "TO",
            R.string.tonga,
            "+676",
            R.drawable.flag_to,
            "TOP",
            "T$"
        ),
        CountryPicker.CountryModel(
            "TR",
            R.string.turkey,
            "+90",
            R.drawable.flag_tr,
            "TRY",
            "₺"
        ),
        CountryPicker.CountryModel(
            "TT",
            R.string.trinidad_and_tobago,
            "+1",
            R.drawable.flag_tt,
            "TTD",
            "TT$"
        ),
        CountryPicker.CountryModel(
            "TV",
            R.string.tuvalu,
            "+688",
            R.drawable.flag_tv,
            "AUD",
            "AU$"
        ),
        CountryPicker.CountryModel(
            "TW",
            R.string.taiwan,
            "+886",
            R.drawable.flag_tw,
            "TWD",
            "NT$"
        ),
        CountryPicker.CountryModel(
            "TZ",
            R.string.tanzania_united_republic_of,
            "+255",
            R.drawable.flag_tz,
            "TZS",
            "TSh"
        ),
        CountryPicker.CountryModel(
            "UA",
            R.string.ukraine,
            "+380",
            R.drawable.flag_ua,
            "UAH",
            "₴"
        ),
        CountryPicker.CountryModel(
            "UG",
            R.string.uganda,
            "+256",
            R.drawable.flag_ug,
            "UGX",
            "USh"
        ),
        CountryPicker.CountryModel(
            "UM",
            R.string.u_s_minor_outlying_islands,
            "+1",
            R.drawable.flag_um,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "US",
            R.string.united_states,
            "+1",
            R.drawable.flag_us,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "UY",
            R.string.uruguay,
            "+598",
            R.drawable.flag_uy,
            "UYU",
            "${'$'}U"
        ),
        CountryPicker.CountryModel(
            "UZ",
            R.string.uzbekistan,
            "+998",
            R.drawable.flag_uz,
            "UZS",
            "so'm"
        ),
        CountryPicker.CountryModel(
            "VA",
            R.string.holy_see_vatican_city_state,
            "+379",
            R.drawable.flag_va,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "VC",
            R.string.saint_vincent_and_the_grenadines,
            "+1",
            R.drawable.flag_vc,
            "XCD",
            "$"
        ),
        CountryPicker.CountryModel(
            "VE",
            R.string.venezuela_bolivarian_republic_of,
            "+58",
            R.drawable.flag_ve,
            "VEF",
            "Bs"
        ),
        CountryPicker.CountryModel(
            "VG",
            R.string.virgin_islands_british,
            "+1",
            R.drawable.flag_vg,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "VI",
            R.string.virgin_islands_u_s,
            "+1",
            R.drawable.flag_vi,
            "USD",
            "$"
        ),
        CountryPicker.CountryModel(
            "VN",
            R.string.vietnam,
            "+84",
            R.drawable.flag_vn,
            "VND",
            "₫"
        ),
        CountryPicker.CountryModel(
            "VU",
            R.string.vanuatu,
            "+678",
            R.drawable.flag_vu,
            "VUV",
            "Vt"
        ),
        CountryPicker.CountryModel(
            "WF",
            R.string.wallis_and_futuna,
            "+681",
            R.drawable.flag_wf,
            "XPF",
            "₣"
        ),
        CountryPicker.CountryModel(
            "WS",
            R.string.samoa,
            "+685",
            R.drawable.flag_ws,
            "WST",
            "WS$"
        ),
        CountryPicker.CountryModel(
            "XK",
            R.string.kosovo,
            "+383",
            R.drawable.flag_xk,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "YE",
            R.string.yemen,
            "+967",
            R.drawable.flag_ye,
            "YER",
            "﷼"
        ),
        CountryPicker.CountryModel(
            "YT",
            R.string.mayotte,
            "+262",
            R.drawable.flag_yt,
            "EUR",
            "€"
        ),
        CountryPicker.CountryModel(
            "ZA",
            R.string.south_africa,
            "+27",
            R.drawable.flag_za,
            "ZAR",
            "R"
        ),
        CountryPicker.CountryModel(
            "ZM",
            R.string.zambia,
            "+260",
            R.drawable.flag_zm,
            "ZMW",
            "ZK"
        ),
        CountryPicker.CountryModel(
            "ZW",
            R.string.zimbabwe,
            "+263",
            R.drawable.flag_zw,
            "USD",
            "$"
        )
    )
}